### ISSUE TITLE
Does the 7941E read HID Prox Card II type cards?

### ISSUE THREAD

**Issue by exabrial** [gutierrezps/gwiot7941e#2]
The documentation claims it has a bit for HID, but I can't seem to find anyone reading prox cards with this device. Thank you!

**Comment by gutierrezps** [comment]
Unfortunately I can't provide an answer since I don't have this type of card to test. Can you link this documentation you've mentioned?

**Comment by exabrial** [comment]
I'm looking around for some technical documentation, but here's the first datasheet: https://www.hidglobal.com/system/files/doc_eol_expired_files/prox-proxcard-ii-card-ds-en.pdf

They are outdated and insecure, as the transmit the card's number in clear text and do not do any authentication (in either direction). Nevertheless, these types of cards are pretty common in the USA.

**Comment by exabrial** [comment]
https://www.hidglobal.com/sites/default/files/hid-understanding_card_data_formats-wp-en.pdf

**Comment by gutierrezps** [comment]
> The documentation claims it has a bit for HID

I thought it was some documentation about the 7941E.

According to [this comment on Quora](https://www.quora.com/What-frequency-does-a-standard-HID-access-card-use-Is-it-125-kHz-13-56-MHz-or-NFC/answer/Rosen-Georgiev-1), HID Prox II is 125 kHz, so I think it can be read by the 7941E.

If you could test it and report, it would be great.

**Comment by exabrial** [comment]
sweet. I have a 7941E coming from china

**Comment by gutierrezps** [comment]
@exabrial did it work?

**Comment by exabrial** [comment]
Because of 'rona, it took months to arrive, but it did a few weeks ago. Unfortunately it did not. Still looking for a solution that can read proxcards :/ Let me know if you ever find something

**Comment by gutierrezps** [comment]
If it's not 125kHz then it might be 13.56MHz, which can be read with RC522 modules. Those are more popular than 125kHz modules, so you can give it a try.

**Comment by exabrial** [comment]
It's definitely 125khz, says on the back of the proxcard. The data encoding format just isn't supported :(
