### ISSUE TITLE
Fritzing Library

### ISSUE THREAD

**Issue by FraatGIT** [gutierrezps/gwiot7941e#3]
Hallo, 

1st great project, thanks. Did you have a Fritzing library for the Gwiot Interface? can you please share it with us?

Thanks.

**Comment by gutierrezps** [comment]
I have made only a breadboard SVG to draw the connections. I've just added the SVG file to the docs folder, feel free to create a Frizing module.

https://github.com/gutierrezps/gwiot7941e/blob/master/doc/7941e_module.svg
